trigger: none  

pool:
  name: 'Default'
  demands:
    - agent.name -equals instance-20241104-101945

variables:
  GCP_SERVICE_CONNECTION: 'mygcpconnection'
  Working_Directory: '$(System.DefaultWorkingDirectory)/gke-cluster'
  Project_GCP: 'velvety-gearbox-439710-c9'

steps:

- script: |
    terraform destroy -input=false -auto-approve
  workingDirectory: $(Working_Directory)
  displayName: 'Terraform destroy'
