trigger:
  branches:
    include:
      - main  

pool:
  name: 'Default'
  demands:
    - agent.name -equals instance-20241104-101945

variables:
  GOOGLE_APPLICATION_CREDENTIALS: '$(System.DefaultWorkingDirectory)/gcp-key.json'

steps:
- checkout: self  

- script: echo "$(GOOGLE_CREDENTIALS)" > $(GOOGLE_APPLICATION_CREDENTIALS)
  displayName: 'Создание файла с ключом Google Cloud'

- script: |
    echo "Contents of $(System.DefaultWorkingDirectory)/gke-cluster:"
    ls -al $(System.DefaultWorkingDirectory)/gke-cluster
  displayName: 'List contents of gke-cluster directory'
- task: TerraformTaskV4@4
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'init'

- task: TerraformTaskV4@4
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'validate'

- task: TerraformTaskV4@4
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'plan'

- task: TerraformTaskV4@4
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'apply'
    commandOptions: '-auto-approve'