trigger:
  branches:
    include:
      - main  

pool:
  name: 'Default'
  demands:
    - agent.name -equals instance-20241104-101945

variables:
  GOOGLE_APPLICATION_CREDENTIALS: '$(System.DefaultWorkingDirectory)/gcp-key.json'

steps:
- checkout: self  

- script: echo "$(GOOGLE_CREDENTIALS)" > $(GOOGLE_APPLICATION_CREDENTIALS)
  displayName: 'Создание файла с ключом Google Cloud'


- task: TerraformTaskV4@4
  inputs:
    provider: "gcp"
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'init'
    backendType: 'gcs'
    backendBucketName: 'bucket-for-tfstate-and-azure-pipeline'
    backendPrefix: 'terraform/state'
    

- task: TerraformTaskV4@4
  inputs:
    provider: "gcp"
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'validate'

- task: TerraformTaskV4@4
  inputs:
    provider: "gcp"
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'plan'

- task: TerraformTaskV4@4
  inputs:
    provider: "gcp"
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'apply'
    commandOptions: '-auto-approve'
    
