trigger:
  branches:
    include:
      - main  

pool:
  name: 'Default'
  demands:
    - agent.name -equals instance-20241104-101945

steps:
- checkout: self  

- script: |
    echo "Hello, Azure DevOps!"
    echo "Pipeline запущен успешно."
  displayName: 'Приветственное сообщение'
