trigger: none 

pool:
  name: 'Default'
  demands:
    - agent.name -equals instance-20241104-101945

variables:
  PROJECT_ID: 'velvety-gearbox-439710-c9'  
  CLUSTER_NAME: 'test-gke-cluster' 
  REGION: 'us-central1'  
  ZONE: 'us-central1-a'

steps:
- task: DownloadSecureFile@1
  name: gcpKeyFile
  inputs:
    secureFile: 'velvety-gearbox-439710-c9-56ac3fa77c53.json'


- script: |
      echo "Creating GKE Cluster..."
      gcloud container clusters create $CLUSTER_NAME \
        --region $REGION \
        --num-nodes=1 \
        --machine-type=e2-small \  
  displayName: 'Create GKE Cluster'

- script: |
      echo "Getting credentials for GKE Cluster..."
      gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION
  displayName: 'Get GKE Cluster Credentials'


