trigger:
  branches:
    include:
      - main  

pool:
  name: 'Default'
  demands:
    - agent.name -equals instance-20241104-101945

steps:
- checkout: self  

- task: TerraformTaskV4@4
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'init'

- task: TerraformTaskV4@4
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'validate'

- task: TerraformTaskV4@4
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'plan'

- task: TerraformTaskV4@4
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/gke-cluster'
    command: 'apply'
    commandOptions: '-auto-approve'