trigger:
  branches:
    include:
      - main  

pool:
  name: 'Default'
  demands:
    - agent.name -equals instance-20241104-101945

variables:
  PROJECT_ID: 'velvety-gearbox-439710-c9'  
  CLUSTER_NAME: 'test-gke-cluster' 
  REGION: 'us-central1'  
  ZONE: 'us-central1-a'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'velvety-gearbox-439710-c9-56ac3fa77c53.json'

- script: |
      echo "Installing Google Cloud SDK..."
      sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
      echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      sudo apt-get update && sudo apt-get install -y google-cloud-sdk
  displayName: 'Install Google Cloud SDK'

- script: |
      echo "Authenticating to Google Cloud..."
      gcloud auth activate-service-account --key-file=$(Agent.TempDirectory)/$(gcpKeyFile.secureFilePath)
      gcloud config set project $PROJECT_ID
  displayName: 'Authenticate to Google Cloud'

- script: |
      echo "Creating GKE Cluster..."
      gcloud container clusters create $CLUSTER_NAME \
        --region $REGION \
        --num-nodes=2 \
        --enable-ip-alias
  displayName: 'Create GKE Cluster'

- script: |
      echo "Getting credentials for GKE Cluster..."
      gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION
  displayName: 'Get GKE Cluster Credentials'


